gen.py generated incorrect bech32 addresses!

